browser=chrome
baseUrl=https://trade.mb.io
marketingUrl=https://mb.io/en-AE
implicitWait=10
explicitWait=20
pageLoadTimeout=30
screenshotPath=test-output/screenshots/
reportPath=test-output/reports/
loginUrl=https://trade.mb.io/login
registerUrl=https://trade.mb.io/register